
/*
| Author          | Project Somedays                      
| Title           | WCCChallenge 2025 Week 31 - Drive 
| 📅 Started      | 2025-04-28       
| 📅 Completed    | 2025-04-28        
| 🕒 Taken        | ~3hrs of vibe-coding like crazy                                  
| 🤯 Concept      | Trailer Driving Sim       
| 🔎 Focus        | Driving physics... but also because vibe-coding I'm none the wiser 😅     

Genuinely need to practice driving with a trailer for work coming up... Thought a sim could be handy!

Made for Sableraph's weekly creative coding challenges, reviewed weekly on https://www.twitch.tv/sableraph

See other submissions here: https://openprocessing.org/curation/78544

Join The Birb's Nest Discord community! https://discord.gg/g5J6Ajx9Am

📦 Resources 📦
- https://www.freepik.com/free-vector/cars-top-view_2874294.htm#fromView=keyword&page=1&position=6&uuid=4cdd633b-46ac-47f1-b2ab-58084125d37d&query=Semi+Truck+Top+View
- https://www.freepik.com/free-vector/topview-boat_23721451.htm#fromView=keyword&page=1&position=0&uuid=0336e72b-5299-4f28-ab5d-be2718fbf55b&query=Boat+Top+View
- https://www.freepik.com/free-vector/swedish-columar_23722219.htm#fromView=keyword&page=1&position=4&uuid=786585a3-757b-48f2-bcd0-7ee6165441d5&query=Tree+Top+View
- End Screen were generated by me in Night Cafe: https://creator.nightcafe.studio/my-creations

📝 TODO:
- [ ] Introduce trees into the carpark that you have to navigate
- [ ] Introduce damage
- [ ] Fix the reversing physics... the trailer should turn depending on angle, not just when the car turns
- [ ] Sound Effects

*/

// Game variables
const trailerGap = 1.1;
const maxSpeed = 5;
const hitBoxOverlap = 0.4;
let car, trailer;

let hitBoatRamp, hitWater, hitTargetWater;

let hitWaterDetected = false;
let hitBoatRampDetected = false;
let hitTargetWaterDetected = false;



let isJackknifed = false; // New: Flag to track jack-knifing state
let JACKKNIFE_ANGLE_THRESHOLD;

// load images
let imgJackKnifed, imgTooMuchDamage, imgInTheDrink, imgSuccess;
let imgCar, imgTrailer;
let vehicleLength;


function preload(){
  imgJackKnifed = loadImage("Jacknifed.png");
  imgTooMuchDamage = loadImage("Too Much Damage.png");
  imgInTheDrink = loadImage("In The Drink.png");
  imgCar = loadImage("Car.png");
  imgTrailer = loadImage("Boat.png");
  imgSuccess = loadImage("Success.png");
}

// --- Setup Function ---
function setup() {
    // Set canvas size
    createCanvas(windowWidth, windowHeight);
    imageMode(CENTER);
    rectMode(CENTER);

    // Define hitboxes for map elements
    hitBoatRamp = {
        x: width/2,
        y: 0.75 * height,
        w: width/5,
        h: 0.75 * height / 3
    };

    hitWater = {
        x: width/2,
        y: 0.75 * height + (1 - 0.75) * height/2,
        w: width,
        h: (1 - 0.75) * height
    };

    hitTargetWater = {
        x: width/2,
        y: 0.75 * height + (1 - 0.75) * height/2,
        w: width/5, // Same width as ramp for alignment
        h: (1 - 0.75) * height
};

    vehicleLength = min(width, height)/15;

    JACKKNIFE_ANGLE_THRESHOLD = PI * 0.75; // 135 degrees

    // Initial position of car (center of canvas)
    car = new DrivingBiz(width/2, height/2, vehicleLength, 2*vehicleLength, imgCar, false, 0, 100)
    let hitchPoint = car.calculateHitchPoint();

    // Set trailer's initial position so its hitch point aligns with car's hitch point
    trailer = new DrivingBiz(hitchPoint.x, hitchPoint.y, vehicleLength, 2*vehicleLength, imgTrailer, true, 0.98, 100)
    trailer.calculateHitchPoint();
    trailer.angle = car.angle; // Trailer starts aligned with the car

    
}



// --- Draw Function ---
function draw() {
    background("#060707");
    drawMap();

    handleKeyPresses();

   
    car.update();
    car.show();

    updateTrailer(car, trailer);

    trailer.show();

    evaluateSuccess(car, trailer);
  
    // debug
    // fill(255, 0, 0);
    // circle(car.calculateHitchPoint().x, car.calculateHitchPoint().y, 5);
    // fill(0, 255, 0);
    // circle(trailer.calculateHitchPoint().x, trailer.calculateHitchPoint().y, 5);
}

function evaluateSuccess(){
  let success = car.isOnBoatRamp() && trailer.isInTargetWater();
  
  if(success) {
    showEndScreen(imgSuccess);
    return;
  }

  let isInTheDrink = car.isInWater() || trailer.isInWater() || car.isInTargetWater();
  if(isInTheDrink){
    showEndScreen(imgInTheDrink);
    return;
  }
}

    
function showEndScreen(img){
  image(img, width/2, height/2, height * img.width / img.height, height)
}


// Fixed handleKeyPresses function
function handleKeyPresses(){
  car.turningDir = 0;
  car.isAccelerating = false;

  // Forward
  if(keyIsDown(UP_ARROW)){
    car.isAccelerating = true;
    car.isDrivingForward = true;
  }

  // Backward
  if(keyIsDown(DOWN_ARROW)){
    car.isDrivingForward = false;
    car.isAccelerating = true;
  }

  // user presses forward and back at once?? 😅
  if(keyIsDown(UP_ARROW) && keyIsDown(DOWN_ARROW)){
    car.isDrivingForward = true;
    car.isAccelerating = false;
  }

  // Turn left
  if(keyIsDown(LEFT_ARROW)) car.turningDir = -1;
  // Turn Right
  if(keyIsDown(RIGHT_ARROW)) car.turningDir = 1;
  // Try to turn both directions at once 😅
  if(keyIsDown(LEFT_ARROW) && keyIsDown(RIGHT_ARROW)) car.turningDir = 0;
}

function drawMap(){
  // water
  let waterStart = 0.75;
  fill("#38afcd");
  rect(width/2, waterStart * height + (1 - waterStart) * height/2 , width, (1 - waterStart) * height);
  
  // ramp
  fill("#3b4747")
  rect(width/2, waterStart * height, width/5, waterStart * height / 3);

}